# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ngFS0T1Ve2dmHFy73M5LK_8gprhMO1Gv
"""

print("나는 신정호다.")